---
- name: Update all servers
  hosts: all
  become: yes

  tasks:
  - name: Install httpd 
    package:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started

  - name: enable httpd
    service:
      name: httpd
      enabled: yes
