---
- name: Update all servers
  hosts: all
  become: yes

  tasks:
  - name: Update page on Amazon
    copy:
      src: amazon.html
      dest: /var/www/html
    when: ansible_distribution == "Amazon"  

  - name: Update page on Ubuntu
    copy:
      src: ubuntu.html
      dest: /var/www/html
    when: ansible_distribution == "Ubuntu"
